- Includes:
    - ./refs/core/rpfs/**/*.rpf
    - ./rpfs/**/*.rpf
  CompileTargets:
    - Input: ./rpfs/Omnius.Axis.Models/Omnius.Axis.Models.rpf
      Output: ./src/Omnius.Axis.Models/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Axis.Engines/Omnius.Axis.Engines.Internal.Models.rpf
      Output: ./src/Omnius.Axis.Engines/Implementations/Internal/Models/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Axis.Remoting/Omnius.Axis.Remoting.rpf
      Output: ./src/Omnius.Axis.Remoting/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Axis.Interactors/Omnius.Axis.Interactors.Models.rpf
      Output: ./src/Omnius.Axis.Interactors/Models/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Axis.Interactors/Omnius.Axis.Interactors.Internal.Models.rpf
      Output: ./src/Omnius.Axis.Interactors/Implementations/Internal/Models/_RocketPack/_Generated.cs
