- Includes:
    - ./refs/core-cs/rpfs/**/*.rpf
    - ./rpfs/**/*.rpf
  CompileTargets:
    - Input: ./rpfs/Omnius.Axus.Messages/Omnius.Axus.Messages.rpf
      Output: ./src/Omnius.Axus.Messages/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Axus.Remoting/Omnius.Axus.Remoting.rpf
      Output: ./src/Omnius.Axus.Remoting/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Axus.Core/Omnius.Axus.Core.Engine.Models.rpf
      Output: ./src/Omnius.Axus.Core/Engine/Models/_RocketPack/_Generated.cs
    - Input: ./rpfs/Omnius.Axus.Core/Omnius.Axus.Core.Interactors.Models.rpf
      Output: ./src/Omnius.Axus.Core/Interactors/Models/_RocketPack/_Generated.cs
